### ISSUE TITLE
nixnote building error with opencv-3.0

### ISSUE THREAD

**Issue by zhtengw** [mroess/overlay#1]
Nixnote build failed with opencv-3.0 : 

/var/tmp/portage/app-misc/nixnote2-2.0_beta4/work/Nixnote2-2.0-beta4/dialog/webcamcapturedialog.cpp:46: undefined reference to `cv::VideoCapture::VideoCapture(int)'
collect2: error: ld returned 1 exit status
Makefile.Release:634: recipe for target 'nixnote2' failed

When I downgrade opencv to version 2.4, no errors any more.
So, the dependency of the opencv for nixnote should be media-libs/opencv:0/2.4 .

**Comment by mroess** [comment]
Thank you for reporting. I will fix that.
